steps:
  - id: docker build
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--no-cache', '-t', 'asia.gcr.io/$PROJECT_ID/snapscale-explorer-middleware:${_IMAGE_TAG}', '.']
  - id: docker push latest
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia.gcr.io/$PROJECT_ID/snapscale-explorer-middleware:${_IMAGE_TAG}']
