steps:
  - id: docker build
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia.gcr.io/$PROJECT_ID/snapscale-explorer-middleware:latest', '.']
  - id: docker push latest
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia.gcr.io/$PROJECT_ID/snapscale-explorer-middleware:latest']
